version: 2

models:
  - name: stg_standings
    description: "Classements nettoyés par ligue"
    columns:
      - name: team_id
        tests: [not_null]
      - name: league
        tests:
          - not_null
          - accepted_values:
              values: ['EPL', 'LIGUE1', 'BUNDESLIGA']
      - name: points
        tests: [not_null]

  - name: stg_matches
    description: "Matchs terminés de la semaine"
    columns:
      - name: match_id
        tests: [not_null, unique]
      - name: result
        tests:
          - accepted_values:
              values: ['HOME_WIN', 'AWAY_WIN', 'DRAW']
